apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8apps.fullname" . }}-deploy
  labels:
    {{- include "k8apps.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "k8apps.selectorLabels" . | nindent 6 }}
      tier: {{ include "k8apps.name" . }}
  revisionHistoryLimit: 0
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8apps.selectorLabels" . | nindent 8 }}
        tier: {{ include "k8apps.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{/* serviceAccountName: {{ include "k8apps.serviceAccountName" . }} */}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.containers.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            #override config.js file
            - name: "{{ ((.Values.containers).volumeMounts).name }}"
              mountPath: "{{ ((.Values.containers).volumeMounts).mountPath }}"
              subPath: "{{ ((.Values.containers).volumeMounts).subPath }}"
          ports:
            - name: http
              containerPort: {{ .Values.containers.ports.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.volumes.name }}
          configMap:
            name: {{ .Values.volumes.configMapName }}
